package edu.utap.weatherwizard.model

import android.util.Log
import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class CityMeta(
    // Auth information
    var ownerName: String = "",
    var ownerUid: String = "",
    var uuid : String = "",
    var city: String = "",
    var state: String = "",
    var favorite: Boolean = false,
    var latitude: String = "",
    var longitude: String = "",
    var home: Boolean = false,
    var units: String = "",
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
) {
    override fun equals(other: Any?) : Boolean =
        if (other is CityMeta) {
            Log.d("XXX",(ownerName == other.ownerName).toString() + " " + (ownerUid == other.ownerUid).toString() + " " +
                    (uuid == other.uuid).toString() + " " + (city == other.city) + " " +
                    (state == other.state) + " " + (latitude == other.latitude) + " " + (longitude == other.longitude)
            )
            (ownerName == other.ownerName)
                    && (ownerUid == other.ownerUid)
                    && (uuid == other.uuid)
                    && (city == other.city)
                    && (state == other.state)
                    && (latitude == other.latitude)
                    && (longitude == other.longitude)
        } else {
            false
        }

    override fun hashCode(): Int {
        var result = ownerName.hashCode()
        result = 31 * result + ownerUid.hashCode()
        result = 31 * result + uuid.hashCode()
        result = 31 * result + city.hashCode()
        result = 31 * result + state.hashCode()
        result = 31 * result + latitude.hashCode()
        result = 31 * result + longitude.hashCode()
        return result
    }
}
