package edu.utap.weatherwizard.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class Rating(
    // AuthWrap information
    var name: String = "",
    var ownerUid: String = "",
    // Text
    var rating: Int = -1,
    // Text
    var city: String="",
    var state: String="",
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)

data class CityRating(
    var avgRating: Double = 0.0,
    var city: String="",
    var state: String="",
)