package edu.utap.weatherwizard.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class UnitsMeta (
    var ownerName: String = "",
    var ownerUid: String = "",
    var units: String = "",
    @ServerTimestamp
    val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId
    var firestoreID: String = ""
)